spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.mybatis: debug
